# Generated by Django 3.0.3 on 2020-02-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200, null=True)),
                ('even_date', models.DateField(null=True)),
                ('event_time', models.TimeField()),
                ('location', models.CharField(max_length=200)),
                ('ticket_price', models.FloatField(blank=True, default=None, null=True)),
                ('ticket_amount', models.IntegerField(blank=True, default=None, null=True)),
                ('picture', models.FileField(default='', upload_to='')),
                ('is_popular', models.BooleanField(null=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainshop.Category')),
            ],
        ),
    ]
