# Generated by Django 3.0.2 on 2020-03-07 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='even_date',
            field=models.DateField(null=True),
        ),
    ]
