# Generated by Django 3.0.3 on 2020-02-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0002_auto_20200228_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='picture',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
