# Generated by Django 3.0.3 on 2020-03-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0003_auto_20200307_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ticket_sold',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
