# Generated by Django 3.0.3 on 2020-02-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0004_auto_20200228_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
