# Generated by Django 3.0.3 on 2020-03-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0004_event_ticket_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_sold',
            field=models.IntegerField(default=0),
        ),
    ]
