# Generated by Django 3.0.3 on 2020-02-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0005_auto_20200229_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
