# Generated by Django 3.0.3 on 2020-03-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainshop', '0005_auto_20200309_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticket_sold',
            field=models.IntegerField(null=True),
        ),
    ]
